### ISSUE TITLE
Allowing other configuration formats?

### ISSUE THREAD

**Issue by Amaras** [papi-web-org/papi-web#8]
I propose allowing expert users to use a format they could be more comfortable with.

The main trouble I have with INI files is the lack of a formal speciication, and as such, I recommend using a format with a formal specification, such as YAML or TOML, both of which have either a well-known library or an stdlib module associated with its parsing.

This would imply writing and maintaining two different parsers, as well as the documentation for both or more formats (if we so decide, although most likely only the physical structure of the configuration file would change), so the workload would probably increase.

This is definitely not a priority for now, but could help with flexibility.

**Comment by pascalaubry** [comment]
IMHO everything should eventually be stored in the database so using text formats will not be needed anymore.
@Amaras Close if OK with this.

**Comment by Amaras** [comment]
Text formats are still the basis of our setup, so we'll see if we need more config formats, especially until we have a config builder.

**Comment by Amaras** [comment]
After careful consideration, I agree we don't need to work on it right now, although I might reopen it some time in the future.
